branches:
  only:
    - master
    - devlopment
    - test
language: minimal
sudo: required
services:
  - docker
before_install:
  - docker build --rm -f "Dockerfile" -t bibata_cursor:latest .
deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file: "Bibata_build.zip"
  skip_cleanup: true
  draft: true
env:
  global:
    secure: UPogwj/1xbHuK7VNhjF3L5Wu1egWUiSlh5YPxk6Gq33WytRDV0EHOhx77iO2BJSuDEV9wo/kVdiFFdHESMD9KmqcNAvD0o6knh3qwBUTYNpOP901oCYUsX76IS1cYWLvKIkJ7ynRbJxxKt8yRt3LBErfHxfL6McCQov2u8E1X59XHic/f63cE15xeyALQRFW8o4BY4DOD0HLsT1b1LNnleq147a4s+jNu3iyGqqH1M15lXlBQLxNH3OW6XaMlbQvsbUCtnnoIvZ3WiikZ6WqIgJLXTNh6nIGxfT5KEs8HUhUK4RfFsuL/pm0iQuYH6E7xVol/u9pL3yWzKK+6B2r3NEl1nUKrrn7KYlq6dnpDInpV6nTyq3J75BpwUaK0Q0YVO/c7ALzGgFfR4KnGMB5jtqddY+bu6zJNkanIJS4a1NCQ+cHE4dvicUHOUaGHoVPCZy8bTWRSnFwcOgDmqP+QmAE+kQXZklwyIG1cVdfvfoi/eKFWrcCOAJe0t1xe1CQ5kOg3hbn8yEmQGlRvqAI+/xlAdj6qVBDrOrg4de1Ha9xSKYheeNosSot7Ca5THtWlugleS3txcDzdFj7ghc0JwNXcQcy2nS9f+fsm2G1GsEC8ctlJgeT0/as+ze1lPtCAKluCGLYh0F9fzrZDdJOQCUAgFdDqpL9h5J1M3tq71w=
