branches:
  only:
    - master
    - devlopment
language: minimal
sudo: required
services:
  - docker
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build --rm -f "Dockerfile" -t bibata_cursor:latest .
env:
  global:
    - secure: ZEoa8wCPp0bHbE3mkM33NF1JDGXa4sF2gn1oneEdAVKWAYsFvn8KkAzRQlIagOyGdFqM3I409xVEQ2hF6S3LANMFj++PkpNfHos5aQdrLStR9V96gFRpFosYhh6zPiA2x9IkLT0kyDN7b6Rnpz9dzF9cbPk/MbDZieb8ZNgl1/fmJAubyEg3nqdVZ8LX2jrST6v4XQCbU8+m5e+uh5BT+io2CxdXlUQzZNolubE8o2b41dDqNcdbLUbjT3KrcSkEwUUIHZeSyckRdeHEggbluTsu3/+sch8kjFTAsk9cvl1fyh/fg+Jeoz9YV9cIf0k7bSv+1Y4X0GGZxGvk00nfHeJ96rGLZ+JRLSPeiKkb1FN8TPstEu2AJmLCeVRX94zbChmETv8M0lbJB4PsES2lxJoCJWtBRrCqDuaSn6f/+IhEdb6uTf4RGFFfxS1WNIjUHsbeg2WyQ2qoCusN9WTsdB17y7hNruuH5APQAYbbPVKJXNckpdHsdH86x5/2px3PbFXtae1Twq/9aDAGDkMd/lCJlLez3xpxTmNjSBRm39x7xXDAoRToJY9U+HKsbW1VHNgmIP0U1i5MgJQhP8hWQrEJNqO7yqZmrvJ0/y8i61j5WGVLeZaYClNB2/IWSeQ6fGoieaWg/LspnhQTG5p0FsfgmlRzy+WxMM54SZXIo10=
    - secure: KN4iEKMeSnf6P+qY8Y0G1+PCJdyb/G75Y3GbJiEe5FSsbbQnArGvBvaS22oSUPapqpY84rivv1w6+UCAnlJcvqpPoL8hrWQhSkWz3BpkJ+rUA/+LeySc7HWdVhksNn6zR8D9YLxTTXlf+ceBKOZ1XBKv4n4TrA/WPjdwRZYlt0E1IJW2bGs5qOlXqPs8KBN5JYn8gKByhKOzqYiOKszJWssC1nk/WM3kRPf+KW+ngqayR8tWqQjoPQZ4JVyDsJ5SNJz42qBwRNRHUoP23pjHiG3VN0LtWzBqhjSX13jEEMcq9dKRP0U0cYl5kW0arPlZFRQRQe8wZ1ML2aaq0JAyh50LPiD0NT/p6Brk2XKkn0NcOLygKOrC+C7KGZT1qoFObia7vWJjG7U9j59tzhIN/MVebY3vvKtmfC+977dAn89iWJNIFa951BaF8dlHycFVHxOI6PC5n1C2Vn7EVjkeEF3KdvuMv5e6xEqxwnFDzYoXIS6sw9P7IUrplXPZVbsaC5JmsBaHs8OgbIShivsamyNZrhlCIyKIFIp9ydMcmCstdM8qCCBdByQipKDHFuF4JoIxSuWVvZ9ls+mlrRxAc+VrubogHsHlaXwks7/bWtbVVLDahwZmGIOfGdc7dewS3ylWArhtg59ggxj4MZpG8pSJFyWJjI05o4fOy7oox7E=
